config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get   '/login',  to: 'sessions#new'
  post  '/login',  to: 'sessions#create'
  get   '/logout', to: 'sessions#destroy'

  get  '/write',   to: 'posts#new'
  post '/write',   to: 'posts#create'
  get  '/read',    to: 'posts#index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { maximum: 144 }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password

  def self.digest(input)
    Digest::SHA1.hexdigest(input)
  end

  def remember(user)
    user.remember
    self.remember_token = SecureRandom.urlsafe_base64
    user.update_attribute(:remember_digest, User.digest(remember_token.to_s))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(body: params[:post][:body], user_id: current_user.id)
    if @post.save
      redirect_to root_url
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'time to log in.'
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_url if logged_in?
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      if params[:session][:remember_me] == "1"
        remember @user
      else
        forget
      end
      log_in @user
      redirect_to root_path
    else
      flash.now[:danger] = 'access denied'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to write_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent.signed[:remember_token] = user.remember_token
  end

  def forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = session[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def log_out
    session.delete(:user_id)
    forget
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class='footer'>
  <% if logged_in? %>
    <%= link_to 'logout', logout_url %><br>
  <% else %>
    <% if !current_page?('/login') %>
      <%= link_to 'login', login_url %><br><br>
    <% end %>
    <% if !current_page?('/signup') %>
      <%= link_to 'signup', signup_url %><br>
    <% end %>  
  <% end %>
</div>

app/views/layouts/_header.erb
<%= content_tag :div, 'members-only', class: 'title' %>
<% if logged_in? %>
  <div class='header'>
    <%= link_to 'write', write_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= content_tag :div, post.body, class: post %>
  <% if logged_in? %>
    <%= content_tag :div, "--#{User.find_by(id: post.user_id).name}", class: 'author' %>
  <% else %>
    <%= content_tag :div, '--anon', class: 'author' %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post, url: write_path, method: 'post' do |f| %>
  <%= f.label :text, "what's up?" %><br>
  <%= f.text_field :body, class: 'write' %><br>
  <%= f.submit 'publish', class: 'button' %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: '/signup' do |f| %>
  <%= f.label :name, 'handle' %><br>
  <%= f.text_field :name %><br>

  <%= f.label :email, 'mail' %><br>
  <%= f.email_field :email %><br>

  <%= f.label :password, 'pass' %><br>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation, 'confirm' %><br>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit 'signup', class: 'button' %>
<% end %>